# Generated by Django 5.0.6 on 2024-10-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Del Propietario ')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido Del Propietario ')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad Del Propiertario ')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion Del Propiertario ')),
                ('telefono', models.CharField(max_length=100, verbose_name='Telefono Del Propiertario ')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo Del Propiertario ')),
                ('contraseña', models.CharField(max_length=100, verbose_name='Contraseña Del Propiertario ')),
                ('activo', models.BooleanField(default=True, verbose_name='Usuario Activo ')),
            ],
        ),
    ]
