# Generated by Django 5.0.6 on 2024-10-07 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascotas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, verbose_name='Codigo De La Mascota ')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre De La Mascota ')),
                ('especie', models.CharField(max_length=100, verbose_name='Especie De La Mascota ')),
                ('raza', models.CharField(max_length=100, verbose_name='Raza De La Mascota ')),
                ('edad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Edad De La Mascota ')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso De La Mascota ')),
                ('id_propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascota', to='Mascotas_app.propietario')),
            ],
        ),
    ]
