# Generated by Django 5.0.6 on 2024-10-09 19:22

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascotas_app', '0002_mascota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True, verbose_name='Codigo Unico Del Producto')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Del Producto')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción De Su Producto')),
                ('presentacion', models.CharField(max_length=100, verbose_name='Presentacion Del Producto')),
                ('pais_origen', models.CharField(max_length=100, verbose_name='Pais De Donde Viene El Producto')),
                ('activo', models.BooleanField(default=True, verbose_name='Producto Activo ')),
                ('fecha_fabric', models.DateField(default=datetime.date.today, verbose_name='Fecha De Fabricación')),
                ('fecha_vencido', models.DateField(default=datetime.date.today, null=True, verbose_name='Fecha Vencimiento ')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0, help_text='Cantidad De Productos En El Inventario', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
            ],
        ),
        migrations.DeleteModel(
            name='Mascota',
        ),
        migrations.DeleteModel(
            name='Propietario',
        ),
    ]
