# Generated by Django 5.0.6 on 2024-10-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascotas_app', '0003_producto_delete_mascota_delete_propietario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=100, verbose_name='Codigo Unico de Reconocimiento')),
                ('Nombre', models.CharField(db_index=True, max_length=100, verbose_name='Nombre De La Persona')),
                ('Apellido', models.CharField(help_text='Coloque su apellido', max_length=150, verbose_name='Apellido De La Persona')),
                ('Ciudad', models.CharField(db_index=True, default='Soacha', help_text='La Ciudad En Donde Vive', max_length=200)),
                ('Direccion', models.CharField(help_text='Dirección de su vivienda', max_length=200)),
                ('Telefono', models.CharField(help_text='Coloque El Numero De Celular Personal', max_length=50, unique=True, verbose_name=' Numero De Telefono')),
                ('Correo', models.CharField(db_index=True, help_text='Escriba Su Correo Electronico Personal', max_length=200, verbose_name='Correo Electronico')),
                ('Genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('Activo', models.PositiveIntegerField(choices=[(1, 'Activo'), (0, 'Inactivo')], default=True, help_text='Coloque el estado de la persona', verbose_name='Persona Viva')),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
