# Generated by Django 5.0.6 on 2024-10-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascotas_app', '0004_persona_delete_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='Tipo',
            field=models.CharField(choices=[(0, 'Natural'), (1, 'Juridica')], default='Natural', help_text='Coloque su tipo ej: Natural o Juridica', max_length=20, verbose_name='Tipo de Persona'),
        ),
    ]
