# Generated by Django 5.0.6 on 2024-10-11 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascotas_app', '0005_persona_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, verbose_name='Nombre Del Cliente')),
                ('Email', models.EmailField(max_length=254, verbose_name='Correo Del Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Pedido', models.DateField()),
                ('Valor_Pedido', models.IntegerField()),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pedidos', to='Mascotas_app.cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
