# Generated by Django 5.0.6 on 2024-10-11 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascotas_app', '0006_cliente_pedidocliente_delete_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=45, verbose_name='Codigo Del Continente')),
                ('Nombre', models.CharField(max_length=45, verbose_name='Nombre Del Continente')),
            ],
        ),
        migrations.RemoveField(
            model_name='pedidocliente',
            name='Cliente',
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=45, verbose_name='Codigo Del Pais')),
                ('Nombre', models.CharField(max_length=45, verbose_name='Nombre Del Pais')),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Paises', to='Mascotas_app.continente')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=45, verbose_name='Codigo Del Provincia')),
                ('Nombre', models.CharField(max_length=45, verbose_name='Nombre De La Provincia')),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Provincias', to='Mascotas_app.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=45, verbose_name='Codigo Del Municipio')),
                ('Nombre', models.CharField(max_length=45, verbose_name='Nombre Del Municipio')),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Municipios', to='Mascotas_app.provincia')),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='PedidoCliente',
        ),
    ]
