# Generated by Django 5.0.6 on 2024-10-11 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascotas_app', '0007_continente_remove_pedidocliente_cliente_pais_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(db_index=True, help_text='Coloque Sus Nombres (No sus Apellidos)', max_length=100, verbose_name='Nombre Del Cliente')),
                ('Email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Del Cliente')),
            ],
        ),
        migrations.RemoveField(
            model_name='pais',
            name='Cliente',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='Cliente',
        ),
        migrations.RemoveField(
            model_name='provincia',
            name='Cliente',
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Nacimiento', models.DateField(auto_now_add=True, db_index=True, verbose_name='Fecha De Creacion De La Cuenta,')),
                ('Direccion', models.CharField(help_text='Coloque La Dirección En Donde Vive Actualmente', max_length=255, verbose_name='Direccion De Vivienda')),
                ('Usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Nombre_Usuario', to='Mascotas_app.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Continente',
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.DeleteModel(
            name='Provincia',
        ),
    ]
