# Generated by Django 5.0.6 on 2024-10-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascotas_app', '0008_usuario_remove_pais_cliente_remove_municipio_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200, verbose_name='Nombre Del Intructor')),
                ('Profesion', models.CharField(max_length=200)),
                ('Especialidad', models.CharField(max_length=200)),
                ('Fecha_Contratacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Instructores', models.ManyToManyField(related_name='Aprendices', to='Mascotas_app.instructor')),
            ],
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
